// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightsControlService.proto

package lightsControl;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightsControl.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomNumber = 1;</code>
   */
  int getRoomNumber();

  /**
   * <code>bool lightOn = 2;</code>
   */
  boolean getLightOn();

  /**
   * <code>bool roomNotFound = 3;</code>
   */
  boolean getRoomNotFound();
}
