// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightsControlService.proto

package lightsControl;

/**
 * Protobuf type {@code lightsControl.LightResponse}
 */
public  final class LightResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightsControl.LightResponse)
    LightResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LightResponse.newBuilder() to construct.
  private LightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LightResponse() {
    roomNumber_ = 0;
    lightOn_ = false;
    roomNotFound_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            roomNumber_ = input.readInt32();
            break;
          }
          case 16: {

            lightOn_ = input.readBool();
            break;
          }
          case 24: {

            roomNotFound_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lightsControl.lightsControlServiceImpl.internal_static_lightsControl_LightResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lightsControl.lightsControlServiceImpl.internal_static_lightsControl_LightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lightsControl.LightResponse.class, lightsControl.LightResponse.Builder.class);
  }

  public static final int ROOMNUMBER_FIELD_NUMBER = 1;
  private int roomNumber_;
  /**
   * <code>int32 roomNumber = 1;</code>
   */
  public int getRoomNumber() {
    return roomNumber_;
  }

  public static final int LIGHTON_FIELD_NUMBER = 2;
  private boolean lightOn_;
  /**
   * <code>bool lightOn = 2;</code>
   */
  public boolean getLightOn() {
    return lightOn_;
  }

  public static final int ROOMNOTFOUND_FIELD_NUMBER = 3;
  private boolean roomNotFound_;
  /**
   * <code>bool roomNotFound = 3;</code>
   */
  public boolean getRoomNotFound() {
    return roomNotFound_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roomNumber_ != 0) {
      output.writeInt32(1, roomNumber_);
    }
    if (lightOn_ != false) {
      output.writeBool(2, lightOn_);
    }
    if (roomNotFound_ != false) {
      output.writeBool(3, roomNotFound_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roomNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, roomNumber_);
    }
    if (lightOn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, lightOn_);
    }
    if (roomNotFound_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, roomNotFound_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lightsControl.LightResponse)) {
      return super.equals(obj);
    }
    lightsControl.LightResponse other = (lightsControl.LightResponse) obj;

    boolean result = true;
    result = result && (getRoomNumber()
        == other.getRoomNumber());
    result = result && (getLightOn()
        == other.getLightOn());
    result = result && (getRoomNotFound()
        == other.getRoomNotFound());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOMNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getRoomNumber();
    hash = (37 * hash) + LIGHTON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLightOn());
    hash = (37 * hash) + ROOMNOTFOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRoomNotFound());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lightsControl.LightResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightsControl.LightResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightsControl.LightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightsControl.LightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightsControl.LightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightsControl.LightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightsControl.LightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightsControl.LightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightsControl.LightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lightsControl.LightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightsControl.LightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightsControl.LightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lightsControl.LightResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightsControl.LightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightsControl.LightResponse)
      lightsControl.LightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightsControl.lightsControlServiceImpl.internal_static_lightsControl_LightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightsControl.lightsControlServiceImpl.internal_static_lightsControl_LightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightsControl.LightResponse.class, lightsControl.LightResponse.Builder.class);
    }

    // Construct using lightsControl.LightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      roomNumber_ = 0;

      lightOn_ = false;

      roomNotFound_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lightsControl.lightsControlServiceImpl.internal_static_lightsControl_LightResponse_descriptor;
    }

    @java.lang.Override
    public lightsControl.LightResponse getDefaultInstanceForType() {
      return lightsControl.LightResponse.getDefaultInstance();
    }

    @java.lang.Override
    public lightsControl.LightResponse build() {
      lightsControl.LightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public lightsControl.LightResponse buildPartial() {
      lightsControl.LightResponse result = new lightsControl.LightResponse(this);
      result.roomNumber_ = roomNumber_;
      result.lightOn_ = lightOn_;
      result.roomNotFound_ = roomNotFound_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lightsControl.LightResponse) {
        return mergeFrom((lightsControl.LightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lightsControl.LightResponse other) {
      if (other == lightsControl.LightResponse.getDefaultInstance()) return this;
      if (other.getRoomNumber() != 0) {
        setRoomNumber(other.getRoomNumber());
      }
      if (other.getLightOn() != false) {
        setLightOn(other.getLightOn());
      }
      if (other.getRoomNotFound() != false) {
        setRoomNotFound(other.getRoomNotFound());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lightsControl.LightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lightsControl.LightResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int roomNumber_ ;
    /**
     * <code>int32 roomNumber = 1;</code>
     */
    public int getRoomNumber() {
      return roomNumber_;
    }
    /**
     * <code>int32 roomNumber = 1;</code>
     */
    public Builder setRoomNumber(int value) {
      
      roomNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roomNumber = 1;</code>
     */
    public Builder clearRoomNumber() {
      
      roomNumber_ = 0;
      onChanged();
      return this;
    }

    private boolean lightOn_ ;
    /**
     * <code>bool lightOn = 2;</code>
     */
    public boolean getLightOn() {
      return lightOn_;
    }
    /**
     * <code>bool lightOn = 2;</code>
     */
    public Builder setLightOn(boolean value) {
      
      lightOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool lightOn = 2;</code>
     */
    public Builder clearLightOn() {
      
      lightOn_ = false;
      onChanged();
      return this;
    }

    private boolean roomNotFound_ ;
    /**
     * <code>bool roomNotFound = 3;</code>
     */
    public boolean getRoomNotFound() {
      return roomNotFound_;
    }
    /**
     * <code>bool roomNotFound = 3;</code>
     */
    public Builder setRoomNotFound(boolean value) {
      
      roomNotFound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool roomNotFound = 3;</code>
     */
    public Builder clearRoomNotFound() {
      
      roomNotFound_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lightsControl.LightResponse)
  }

  // @@protoc_insertion_point(class_scope:lightsControl.LightResponse)
  private static final lightsControl.LightResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lightsControl.LightResponse();
  }

  public static lightsControl.LightResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LightResponse>
      PARSER = new com.google.protobuf.AbstractParser<LightResponse>() {
    @java.lang.Override
    public LightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LightResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LightResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LightResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public lightsControl.LightResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

