// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightsControlService.proto

package lightsControl;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightsControl.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomNumber = 1;</code>
   */
  int getRoomNumber();
}
