// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightsControlService.proto

package lightsControl;

public final class lightsControlServiceImpl {
  private lightsControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightsControl_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightsControl_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightsControl_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightsControl_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032lightsControlService.proto\022\rlightsCont" +
      "rol\"\"\n\014LightRequest\022\022\n\nroomNumber\030\001 \001(\005\"" +
      "J\n\rLightResponse\022\022\n\nroomNumber\030\001 \001(\005\022\017\n\007" +
      "lightOn\030\002 \001(\010\022\024\n\014roomNotFound\030\003 \001(\0102n\n\024l" +
      "ightsControlService\022V\n\023readRoomLightStat" +
      "us\022\033.lightsControl.LightRequest\032\034.lights" +
      "Control.LightResponse\"\000(\0010\001B\034B\030lightsCon" +
      "trolServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightsControl_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightsControl_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightsControl_LightRequest_descriptor,
        new java.lang.String[] { "RoomNumber", });
    internal_static_lightsControl_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightsControl_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightsControl_LightResponse_descriptor,
        new java.lang.String[] { "RoomNumber", "LightOn", "RoomNotFound", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
