// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heatingControlService.proto

package heatingControl;

public interface HeatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heatingControl.HeatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string heatingStatus = 1;</code>
   */
  java.lang.String getHeatingStatus();
  /**
   * <code>string heatingStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeatingStatusBytes();
}
