// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heatingControlService.proto

package heatingControl;

public interface HeatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heatingControl.HeatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heatingNumber = 1;</code>
   */
  int getHeatingNumber();

  /**
   * <code>bool turnOn = 2;</code>
   */
  boolean getTurnOn();
}
