// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heatingControlService.proto

package heatingControl;

public final class heatingControlServiceImpl {
  private heatingControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heatingControl_HeatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heatingControl_HeatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heatingControl_HeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heatingControl_HeatingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033heatingControlService.proto\022\016heatingCo" +
      "ntrol\"7\n\016HeatingRequest\022\025\n\rheatingNumber" +
      "\030\001 \001(\005\022\016\n\006turnOn\030\002 \001(\010\"(\n\017HeatingRespons" +
      "e\022\025\n\rheatingStatus\030\001 \001(\t2s\n\025heatingContr" +
      "olService\022Z\n\023changeHeatingStatus\022\036.heati" +
      "ngControl.HeatingRequest\032\037.heatingContro" +
      "l.HeatingResponse\"\000(\001B\035B\031heatingControlS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heatingControl_HeatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heatingControl_HeatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heatingControl_HeatingRequest_descriptor,
        new java.lang.String[] { "HeatingNumber", "TurnOn", });
    internal_static_heatingControl_HeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heatingControl_HeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heatingControl_HeatingResponse_descriptor,
        new java.lang.String[] { "HeatingStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
