// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heatingControlService.proto

package heatingControl;

/**
 * Protobuf type {@code heatingControl.HeatingRequest}
 */
public  final class HeatingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:heatingControl.HeatingRequest)
    HeatingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeatingRequest.newBuilder() to construct.
  private HeatingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeatingRequest() {
    heatingNumber_ = 0;
    turnOn_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeatingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            heatingNumber_ = input.readInt32();
            break;
          }
          case 16: {

            turnOn_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return heatingControl.heatingControlServiceImpl.internal_static_heatingControl_HeatingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return heatingControl.heatingControlServiceImpl.internal_static_heatingControl_HeatingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            heatingControl.HeatingRequest.class, heatingControl.HeatingRequest.Builder.class);
  }

  public static final int HEATINGNUMBER_FIELD_NUMBER = 1;
  private int heatingNumber_;
  /**
   * <code>int32 heatingNumber = 1;</code>
   */
  public int getHeatingNumber() {
    return heatingNumber_;
  }

  public static final int TURNON_FIELD_NUMBER = 2;
  private boolean turnOn_;
  /**
   * <code>bool turnOn = 2;</code>
   */
  public boolean getTurnOn() {
    return turnOn_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (heatingNumber_ != 0) {
      output.writeInt32(1, heatingNumber_);
    }
    if (turnOn_ != false) {
      output.writeBool(2, turnOn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (heatingNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, heatingNumber_);
    }
    if (turnOn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, turnOn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof heatingControl.HeatingRequest)) {
      return super.equals(obj);
    }
    heatingControl.HeatingRequest other = (heatingControl.HeatingRequest) obj;

    boolean result = true;
    result = result && (getHeatingNumber()
        == other.getHeatingNumber());
    result = result && (getTurnOn()
        == other.getTurnOn());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEATINGNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getHeatingNumber();
    hash = (37 * hash) + TURNON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTurnOn());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static heatingControl.HeatingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static heatingControl.HeatingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static heatingControl.HeatingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static heatingControl.HeatingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static heatingControl.HeatingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static heatingControl.HeatingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static heatingControl.HeatingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static heatingControl.HeatingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static heatingControl.HeatingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static heatingControl.HeatingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static heatingControl.HeatingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static heatingControl.HeatingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(heatingControl.HeatingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code heatingControl.HeatingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:heatingControl.HeatingRequest)
      heatingControl.HeatingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return heatingControl.heatingControlServiceImpl.internal_static_heatingControl_HeatingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return heatingControl.heatingControlServiceImpl.internal_static_heatingControl_HeatingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              heatingControl.HeatingRequest.class, heatingControl.HeatingRequest.Builder.class);
    }

    // Construct using heatingControl.HeatingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      heatingNumber_ = 0;

      turnOn_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return heatingControl.heatingControlServiceImpl.internal_static_heatingControl_HeatingRequest_descriptor;
    }

    @java.lang.Override
    public heatingControl.HeatingRequest getDefaultInstanceForType() {
      return heatingControl.HeatingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public heatingControl.HeatingRequest build() {
      heatingControl.HeatingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public heatingControl.HeatingRequest buildPartial() {
      heatingControl.HeatingRequest result = new heatingControl.HeatingRequest(this);
      result.heatingNumber_ = heatingNumber_;
      result.turnOn_ = turnOn_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof heatingControl.HeatingRequest) {
        return mergeFrom((heatingControl.HeatingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(heatingControl.HeatingRequest other) {
      if (other == heatingControl.HeatingRequest.getDefaultInstance()) return this;
      if (other.getHeatingNumber() != 0) {
        setHeatingNumber(other.getHeatingNumber());
      }
      if (other.getTurnOn() != false) {
        setTurnOn(other.getTurnOn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      heatingControl.HeatingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (heatingControl.HeatingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int heatingNumber_ ;
    /**
     * <code>int32 heatingNumber = 1;</code>
     */
    public int getHeatingNumber() {
      return heatingNumber_;
    }
    /**
     * <code>int32 heatingNumber = 1;</code>
     */
    public Builder setHeatingNumber(int value) {
      
      heatingNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 heatingNumber = 1;</code>
     */
    public Builder clearHeatingNumber() {
      
      heatingNumber_ = 0;
      onChanged();
      return this;
    }

    private boolean turnOn_ ;
    /**
     * <code>bool turnOn = 2;</code>
     */
    public boolean getTurnOn() {
      return turnOn_;
    }
    /**
     * <code>bool turnOn = 2;</code>
     */
    public Builder setTurnOn(boolean value) {
      
      turnOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool turnOn = 2;</code>
     */
    public Builder clearTurnOn() {
      
      turnOn_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:heatingControl.HeatingRequest)
  }

  // @@protoc_insertion_point(class_scope:heatingControl.HeatingRequest)
  private static final heatingControl.HeatingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new heatingControl.HeatingRequest();
  }

  public static heatingControl.HeatingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeatingRequest>
      PARSER = new com.google.protobuf.AbstractParser<HeatingRequest>() {
    @java.lang.Override
    public HeatingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeatingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeatingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeatingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public heatingControl.HeatingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

