// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitorsControlService.proto

package visitorsControl;

public interface GuestBookServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:visitorsControl.GuestBookServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmationMessage = 1;</code>
   */
  java.lang.String getConfirmationMessage();
  /**
   * <code>string confirmationMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationMessageBytes();
}
