// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitorsControlService.proto

package visitorsControl;

public final class visitorsControlServiceImpl {
  private visitorsControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visitorsControl_VisitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visitorsControl_VisitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visitorsControl_GuestBookServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visitorsControl_GuestBookServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034visitorsControlService.proto\022\017visitors" +
      "Control\"#\n\016VisitorRequest\022\021\n\tguestName\030\001" +
      " \001(\t\"7\n\030GuestBookServiceResponse\022\033\n\023conf" +
      "irmationMessage\030\001 \001(\t2y\n\026visitorsControl" +
      "Service\022_\n\017registerVisitor\022\037.visitorsCon" +
      "trol.VisitorRequest\032).visitorsControl.Gu" +
      "estBookServiceResponse\"\000B\036B\032visitorsCont" +
      "rolServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_visitorsControl_VisitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_visitorsControl_VisitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visitorsControl_VisitorRequest_descriptor,
        new java.lang.String[] { "GuestName", });
    internal_static_visitorsControl_GuestBookServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_visitorsControl_GuestBookServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visitorsControl_GuestBookServiceResponse_descriptor,
        new java.lang.String[] { "ConfirmationMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
