// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitorsControlService.proto

package visitorsControl;

public interface VisitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:visitorsControl.VisitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string guestName = 1;</code>
   */
  java.lang.String getGuestName();
  /**
   * <code>string guestName = 1;</code>
   */
  com.google.protobuf.ByteString
      getGuestNameBytes();
}
