// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAvailabilityControlService.proto

package roomAvailabilityControl;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:roomAvailabilityControl.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
