// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAvailabilityControlService.proto

package roomAvailabilityControl;

public interface RoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:roomAvailabilityControl.RoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomNumber = 1;</code>
   */
  int getRoomNumber();

  /**
   * <code>string roomStatus = 2;</code>
   */
  java.lang.String getRoomStatus();
  /**
   * <code>string roomStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomStatusBytes();
}
